apiVersion: v1
kind: Service
metadata:
  name: {{ template "windocks-sql-proxy.fullname" . }}
  labels:
    app: {{ template "windocks-sql-proxy.name" . }}
    chart: {{ template "windocks-sql-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: tcp
  selector:
    app: {{ template "windocks-sql-proxy.name" . }}
    release: {{ .Release.Name }}
